### ISSUE TITLE
Support of github secrets

### ISSUE THREAD

**Issue by igagis** [ChristopherHX/github-actions-act-runner#9]
Does the runner support github secrets?
I'm getting some weird error when trying to use my `secrets.MYCI_REPO_SSH_KEY` secret, see run:
https://github.com/cppfw/utki/runs/3072012329?check_suite_focus=true

**Comment by ChristopherHX** [comment]
> Does the runner support github secrets?

Technically yes, but it seems the expression interpreter of act has a bug with new lines in a string literal.
```
${{format('echo "{0}" > repo_key_rsa && chmod 600 repo_key_rsa
myci-deploy-debian-ssh-freight.sh --key repo_key_rsa --server gagis.hopto.org --owner cppfw --repo {1} --distro {2} --component main ../lib*__*.deb
', secrets.MYCI_REPO_SSH_KEY, matrix.os, matrix.codename)}}
```

I need to adjust
https://github.com/ChristopherHX/act/blob/44e468defcb3f600c90af16f2e3624bfd72c450d/pkg/runner/expression.go#L21 to include new lines and replace newlines in string literals with `\n` to make the js interpreter happy.

**Comment by igagis** [comment]
This is a showstopper for me. Waiting for the fix!

**Comment by ChristopherHX** [comment]
Please check all your issues against this snapshot:
https://github.com/ChristopherHX/github-actions-act-runner/actions/runs/1034189998

This should work now

**Comment by igagis** [comment]
Unfortunately it still does not work. Though the error now looks a bit different:
https://github.com/cppfw/utki/runs/3078054848?check_suite_focus=true

**Comment by igagis** [comment]
`[ReferenceError: 'PACKAGE_NAME' is not defined ReferenceError: 'PACKAGE_VERSION' is not defined]`

in the original yaml those vars are referenced as `${PACKAGE_NAME}` i.e. as normal `shell` vars. Though the runner changes it to `${{PACKAGE_NAME}}` for some reason, according to the job log.

**Comment by ChristopherHX** [comment]
I found the error, I didn't know that `{` needs to be escaped as `{{` in the format directive (same for }), github does this automatically

Should now generate a script like:, replacing {{ back to { in format (bug of act)
```
echo "undefined" > repo_key_rsa && chmod 600 repo_key_rsa
myci-deploy-debian-ssh-freight.sh --key repo_key_rsa --server gagis.hopto.org --owner cppfw --repo undefined --distro undefined --component main ../lib${PACKAGE_NAME}*_${PACKAGE_VERSION}_*.deb
```
undefined, is shown here because it is from an incomplete workflow

https://github.com/ChristopherHX/github-actions-act-runner/actions/runs/1034574574

Please add the secret `ACTIONS_STEP_DEBUG` with value `true` then you will see even more debug logging.

**Comment by igagis** [comment]
this latest snapshot works!

**Comment by igagis** [comment]
works in release 0.0.3
